package filter

import (
	"regexp"
	"strings"

	"github.com/GrayCodeAI/tokman/internal/core"
)

// BoilerplateFilter removes common boilerplate patterns from source files
// and documents. Compressed to single-token markers so the LLM still
// knows what was removed.
//
// Patterns handled:
//  1. License / copyright headers (SPDX, Apache, MIT, GPL boilerplate)
//  2. Auto-generated file warnings ("Code generated by...", "DO NOT EDIT")
//  3. Repeated copyright notices
//  4. CI/CD configuration boilerplate (GitHub Actions step headers, etc.)
//  5. Protobuf/gRPC auto-generated comments
type BoilerplateFilter struct{}

var (
	// License/copyright block at top of file: detects common SPDX and license text
	licenseHeaderRe = regexp.MustCompile(
		`(?m)^[\s/*#]*(?:` +
			`Copyright\s+(?:\(c\)\s*)?\d{4}|` +
			`SPDX-License-Identifier:|` +
			`Licensed under the|` +
			`This file is part of|` +
			`Permission is hereby granted|` +
			`Redistribution and use in source|` +
			`GNU General Public License|` +
			`MIT License|` +
			`Apache License` +
			`)[^\n]*`,
	)
	// Auto-generated file warnings (first 5 lines typically)
	autoGenRe = regexp.MustCompile(
		`(?i)(?:` +
			`Code generated[^\n]*DO NOT EDIT|` +
			`DO NOT EDIT[^\n]*generated|` +
			`This file was automatically generated|` +
			`Autogenerated by|` +
			`Auto-generated\. Do not edit|` +
			`Generated by protoc|` +
			`Generated by the gRPC|` +
			`\@generated|` +
			`<auto-generated>` +
			`)[^\n]*`,
	)
	// CI/CD step headers — GitHub Actions / GitLab CI noise
	ciStepRe = regexp.MustCompile(
		`(?m)^(?:##\[(?:group|endgroup|section|command|debug)\]|` +
			`\[command\]|` +
			`shell: /bin/bash -e ` +
			`)[^\n]*$`,
	)
	// Protobuf generated comment blocks
	protoGenCommentRe = regexp.MustCompile(
		`(?m)^// Code generated by protoc-gen-[^\n]+$`,
	)
	// Blank comment lines (lines containing only comment markers)
	blankCommentRe = regexp.MustCompile(`(?m)^[\s]*(?://|#|\*|/\*|\*/)\s*$`)
	// Long separator lines (=====, -----, #####, all same char)
	separatorLineRe = regexp.MustCompile(`(?m)^[\s]*([=\-#*~]{10,})\s*$`)
)

// NewBoilerplateFilter creates a boilerplate removal filter.
func NewBoilerplateFilter() *BoilerplateFilter {
	return &BoilerplateFilter{}
}

// Name returns the filter name.
func (f *BoilerplateFilter) Name() string {
	return "boilerplate"
}

// Apply removes detected boilerplate and replaces it with compact markers.
func (f *BoilerplateFilter) Apply(input string, mode Mode) (string, int) {
	if mode == ModeNone {
		return input, 0
	}

	original := core.EstimateTokens(input)
	output := input

	// Replace license header blocks (run of ≥3 consecutive license lines at top)
	output = f.collapseLicenseBlock(output)

	// Replace auto-gen warnings
	output = autoGenRe.ReplaceAllString(output, "[auto-generated]")

	// Replace CI/CD step markers
	output = ciStepRe.ReplaceAllString(output, "")

	// Replace proto-gen comments
	output = protoGenCommentRe.ReplaceAllString(output, "")

	if mode == ModeAggressive {
		// Remove blank comment lines
		output = blankCommentRe.ReplaceAllString(output, "")
		// Remove pure separator lines
		output = separatorLineRe.ReplaceAllString(output, "")
	}

	// Clean up excess blank lines
	output = collapseBlankLines(output, 2)

	saved := original - core.EstimateTokens(output)
	if saved <= 0 {
		return input, 0
	}
	return output, saved
}

// collapseLicenseBlock finds and replaces consecutive license-related comment
// lines at the top of a file with a single compact marker.
func (f *BoilerplateFilter) collapseLicenseBlock(input string) string {
	lines := strings.Split(input, "\n")
	licenseLines := 0
	maxCheckLines := 30 // Only check the first 30 lines for license headers

	check := len(lines)
	if check > maxCheckLines {
		check = maxCheckLines
	}

	for i := 0; i < check; i++ {
		line := lines[i]
		trimmed := strings.TrimSpace(line)
		if trimmed == "" ||
			strings.HasPrefix(trimmed, "//") ||
			strings.HasPrefix(trimmed, "#") ||
			strings.HasPrefix(trimmed, "/*") ||
			strings.HasPrefix(trimmed, "*") ||
			strings.HasPrefix(trimmed, "*/") {
			if licenseHeaderRe.MatchString(line) || strings.HasPrefix(trimmed, "*") || strings.HasPrefix(trimmed, "/*") || strings.HasPrefix(trimmed, "*/") {
				licenseLines++
				continue
			}
		}
		break
	}

	// Only collapse if there are at least 3 license-header lines
	if licenseLines < 3 {
		return input
	}

	// Find the actual end of the license block
	end := 0
	for end < len(lines) {
		trimmed := strings.TrimSpace(lines[end])
		if end >= maxCheckLines || (trimmed != "" &&
			!strings.HasPrefix(trimmed, "//") &&
			!strings.HasPrefix(trimmed, "#") &&
			!strings.HasPrefix(trimmed, "/*") &&
			!strings.HasPrefix(trimmed, "*") &&
			!strings.HasPrefix(trimmed, "*/") &&
			!licenseHeaderRe.MatchString(lines[end])) {
			break
		}
		end++
	}

	if end < 3 {
		return input
	}

	marker := "[license-header: " + itoa(end) + " lines omitted]"
	result := append([]string{marker}, lines[end:]...)
	return strings.Join(result, "\n")
}
